@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana


class User {
- int userId;
- String firstName;
- String lastName
- String phoneNumber
- String email
-String password;
- boolean isAdmin;
- int addressId

boolean customer **;
}

class Order{
int orderId
User user
String comment
Shipping shipping
int cpLength
int cpWidth
String cpRoof
int shLength
int shWidth
int statusId
String status
int shippingId

}


class OrderLine{

int quantity;
}





User --- Order
Order --- OrderLine


@enduml




@enduml