@startuml
'https://plantuml.com/class-diagram
!pragma layout smetana
hide circle
hide methods

class Material
{
materialId
materialPrice
unit
type

}

class Customer
{
name
lastname
phonenumber
address
e-mail
password
}

class Admin
{
name
e-mail
password
phonenumber
}



class Order
{
ordrenummer
shipping
lenght
width
roof
status
}


class Carport
{
price
width
lenght
}

class Shed
{
length
width
}

Customer "1" -- "*" Order
Order "*" -- "1" Carport
Carport "1" -- "1" Shed
Material "*" -- "1" Carport
Material "*" -- "1" Shed
Admin "*" -- "*" Order




@enduml